const TEST_SERVER_BASE_URL = "http://20.244.56.144/evaluation-service";
const WINDOW_SIZE = 10;
const FETCH_TIMEOUT = 1000;

const API_ENDPOINTS = {
  p: `${TEST_SERVER_BASE_URL}/primes`,
  f: `${TEST_SERVER_BASE_URL}/fibo`,
  e: `${TEST_SERVER_BASE_URL}/even`,
  r: `${TEST_SERVER_BASE_URL}/rand`,
};

const AUTH_TOKEN = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJNYXBDbGFpbXMiOnsiZXhwIjoxNzQ4MDY5Njg0LCJpYXQiOjE3NDgwNjkzODQsImlzcyI6IkFmZm9yZG1lZCIsImp0aSI6IjNjMjg2NTE5LWViOGUtNDgwNC1hNWY1LTQ3NzYwNmIzYmM2NiIsInN1YiI6Im1haWwybXV0aHVrdW1hcjAwN0BnbWFpbC5jb20ifSwiZW1haWwiOiJtYWlsMm11dGh1a3VtYXIwMDdAZ21haWwuY29tIiwibmFtZSI6Im11dGh1a3VtYXIgayIsInJvbGxObyI6IjkyNzYyMmJhbDAyOCIsImFjY2Vzc0NvZGUiOiJ3aGVRVXkiLCJjbGllbnRJRCI6IjNjMjg2NTE5LWViOGUtNDgwNC1hNWY1LTQ3NzYwNmIzYmM2NiIsImNsaWVudFNlY3JldCI6InNndERXYUZxeXlaYmt4c2YifQ.DVZMO0QyOpwXvfW5_uCeyDN-6bcCLaW_GWOlnTcdCvs";
module.exports = {
  API_ENDPOINTS,
  WINDOW_SIZE,
  FETCH_TIMEOUT,
  AUTH_TOKEN,
};